# Stages
stages:
  - test
  - publish

# Variables
variables:
  CICD_IMAGE: ${CI_REGISTRY}/naviothera/deployment/cicd:latest
  POSTGRES_IMAGE: 'postgres:10.6-alpine'
  TEST_POSTGRES_DB_NAME: navio_test
  TEST_POSTGRES_PASSWORD: test
  TEST_POSTGRES_USER: test

# Basic library publishing tasks for test/publish
include:
  - project: 'naviothera/deployment'
    ref: master
    file:
      - '/cicd_yaml/lib-with-pg-test-definition.yaml'
      - '/cicd_yaml/app-tests.yaml'
      - '/cicd_yaml/publish-libs-gitlab-maven.yaml'
