# Stages
stages:
  - test
  - publish

# Variables
variables:
  CICD_IMAGE: ${CI_REGISTRY}/naviothera/product/quantumsoft/shared-docker-images/cicd:latest
  POSTGRES_IMAGE: 'postgres:10.6-alpine'
  TEST_POSTGRES_DB_NAME: navio_test
  TEST_POSTGRES_PASSWORD: test
  TEST_POSTGRES_USER: test

# Basic library publishing tasks for test/publish
include:
  - project: 'naviothera/deployment'
    ref: master
    file:
      - '/lib-with-pg-test-definition.yaml'
      - '/app-tests.yaml'
      - '/publish-libs-mymaven.yaml'
